language: generic

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="meson appstream desktop-file-utils libgee-0.8-dev libgranite-dev libgtk-3-dev valac"

install:
 - docker pull elementary/docker:loki
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:loki /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && meson release-build --prefix=/usr  --buildtype=release && cd release-build && ninja"
 - docker pull elementary/docker:loki-unstable
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:loki-unstable /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && rm -rf release-build && meson release-build --prefix=/usr  --buildtype=release && cd release-build && ninja"

script:
 - echo BUILDS PASSED
